/**
 * Validation rule identifiers (specification section 13.3), with two
 * corrections applied:
 *
 *   - Section 8.3 named RULE_AUTHORIZED_CERTIFIER_REQUIRED while section 13.3
 *     named RULE_CERTIFIER_AUTHORIZED for the same rule. The section 13.3 form
 *     is kept, since it matches the naming pattern of its neighbours.
 *
 *   - RULE_OWNERSHIP_UNCHANGED_ON_CUSTODY_TRANSFER is new. Section 8.4 requires
 *     that a custody transfer which also moves ownership be rejected -- that is
 *     the single most important conceptual distinction in the simulation -- but
 *     no rule in section 13.3 enforced it.
 */
export enum ValidationRuleId {
  ACTOR_AUTHORIZED = "RULE_ACTOR_AUTHORIZED",
  ORGANIZATION_ACTIVE = "RULE_ORGANIZATION_ACTIVE",
  ASSET_EXISTS = "RULE_ASSET_EXISTS",
  ASSET_ID_UNIQUE = "RULE_ASSET_ID_UNIQUE",
  CURRENT_OWNER_REQUIRED = "RULE_CURRENT_OWNER_REQUIRED",
  CURRENT_CUSTODIAN_REQUIRED = "RULE_CURRENT_CUSTODIAN_REQUIRED",
  RECEIVER_AUTHORIZED = "RULE_RECEIVER_AUTHORIZED",
  VALID_QUANTITY = "RULE_VALID_QUANTITY",
  AVAILABLE_QUANTITY = "RULE_AVAILABLE_QUANTITY",
  UNIT_COMPATIBLE = "RULE_UNIT_COMPATIBLE",
  VALID_STATE_TRANSITION = "RULE_VALID_STATE_TRANSITION",
  BATCH_NOT_RECALLED = "RULE_BATCH_NOT_RECALLED",
  CERTIFIER_AUTHORIZED = "RULE_CERTIFIER_AUTHORIZED",
  CERTIFICATE_NOT_EXPIRED = "RULE_CERTIFICATE_NOT_EXPIRED",
  DOCUMENT_HASH_PRESENT = "RULE_DOCUMENT_HASH_PRESENT",
  DOCUMENT_ANCHOR_VALID = "RULE_DOCUMENT_ANCHOR_VALID",
  DOCUMENT_METADATA_VALID = "RULE_DOCUMENT_METADATA_VALID",
  SHIPMENT_BEFORE_RECEIPT = "RULE_SHIPMENT_BEFORE_RECEIPT",
  RECEIPT_NOT_DUPLICATED = "RULE_RECEIPT_NOT_DUPLICATED",
  OWNERSHIP_UNCHANGED_ON_CUSTODY_TRANSFER = "RULE_OWNERSHIP_UNCHANGED_ON_CUSTODY_TRANSFER",
  TRANSFORMATION_INPUT_EXISTS = "RULE_TRANSFORMATION_INPUT_EXISTS",
  TRANSFORMATION_OUTPUT_UNIQUE = "RULE_TRANSFORMATION_OUTPUT_UNIQUE",
  TRANSFORMATION_OUTPUT_NOT_GREATER_THAN_INPUT = "RULE_TRANSFORMATION_OUTPUT_NOT_GREATER_THAN_INPUT",
  CORRECTION_REFERENCE_EXISTS = "RULE_CORRECTION_REFERENCE_EXISTS",
  CORRECTION_TARGET_VALID = "RULE_CORRECTION_TARGET_VALID",
  CORRECTION_REASON_REQUIRED = "RULE_CORRECTION_REASON_REQUIRED",
  CORRECTION_INCORRECT_VALUE_MATCHES_EFFECTIVE = "RULE_CORRECTION_INCORRECT_VALUE_MATCHES_EFFECTIVE",
  CORRECTION_VALUE_VALID = "RULE_CORRECTION_VALUE_VALID",
  RECALL_AUTHORIZED = "RULE_RECALL_AUTHORIZED",
  TIMESTAMP_SEQUENCE_VALID = "RULE_TIMESTAMP_SEQUENCE_VALID",
}
