export const TechnicalLabCommandType = {
  TRANSFER_CUSTODY: "LAB_TRANSFER_CUSTODY",
  ISSUE_CERTIFICATE: "LAB_ISSUE_CERTIFICATE",
  POLICY_DEMO: "LAB_POLICY_DEMO",
  CORRECTION: "LAB_QUANTITY_CORRECTION",
  STATE_CHANGE: "LAB_STATE_CHANGE",
} as const;
