import type {
  ScenarioEvidenceStaffAttribution,
  ScenarioPortraitAsset,
  ScenarioStaffProfile,
} from "../../domain/types/scenario";
import { ActorId, LocationId, OrganizationId } from "./organizations";
import { SHIPPING_MANIFEST_ANCHOR_ID } from "./facts";

export const StaffProfileId = {
  PRODUCER_MANAGER: "STAFF_PRODUCER_MANAGER",
  CERTIFICATION_OFFICER: "STAFF_CERTIFICATION_OFFICER",
  LOGISTICS_COORDINATOR: "STAFF_LOGISTICS_COORDINATOR",
  PROCESSING_MANAGER: "STAFF_PROCESSING_MANAGER",
  SHIPPING_CLERK: "STAFF_SHIPPING_CLERK",
  RETAIL_MANAGER: "STAFF_RETAIL_MANAGER",
  REGULATORY_AUDITOR: "STAFF_REGULATORY_AUDITOR",
} as const;

export const PortraitAssetId = {
  PRODUCER_MANAGER: "PORTRAIT_PRODUCER_MANAGER",
  CERTIFICATION_OFFICER: "PORTRAIT_CERTIFICATION_OFFICER",
  LOGISTICS_COORDINATOR: "PORTRAIT_LOGISTICS_COORDINATOR",
  PROCESSING_MANAGER: "PORTRAIT_PROCESSING_MANAGER",
  SHIPPING_CLERK: "PORTRAIT_SHIPPING_CLERK",
  RETAIL_MANAGER: "PORTRAIT_RETAIL_MANAGER",
  REGULATORY_AUDITOR: "PORTRAIT_REGULATORY_AUDITOR",
} as const;

const approvalReference = "TRACECHAIN_PRODUCT_OWNER_IMPLEMENTATION_2026-07-26";

export const coffeePortraitAssets: readonly ScenarioPortraitAsset[] = [
  {
    assetId: PortraitAssetId.PRODUCER_MANAGER,
    sourceType: "AI_GENERATED",
    licenseOrApprovalReference: approvalReference,
    fictionalSubject: true,
    filePath: "media/staff/producer-manager.webp",
    sha256: "e12d002f111b56d9f8209db549c8fd58bc183e4f68f8478b182cbff3a853f616",
    width: 480,
    height: 600,
    format: "webp",
    developmentPlaceholder: false,
  },
  {
    assetId: PortraitAssetId.CERTIFICATION_OFFICER,
    sourceType: "AI_GENERATED",
    licenseOrApprovalReference: approvalReference,
    fictionalSubject: true,
    filePath: "media/staff/certification-officer.webp",
    sha256: "96d744a37b95d82cceb9a6f58399b3a64a3cf7a740621829b7c81bb7bf4c5d11",
    width: 480,
    height: 600,
    format: "webp",
    developmentPlaceholder: false,
  },
  {
    assetId: PortraitAssetId.LOGISTICS_COORDINATOR,
    sourceType: "AI_GENERATED",
    licenseOrApprovalReference: approvalReference,
    fictionalSubject: true,
    filePath: "media/staff/logistics-coordinator.webp",
    sha256: "3863c4f85ced3fee1916ee145ce6f817d30fc9a36ff62f58d18f576d3ad2a95c",
    width: 480,
    height: 600,
    format: "webp",
    developmentPlaceholder: false,
  },
  {
    assetId: PortraitAssetId.PROCESSING_MANAGER,
    sourceType: "AI_GENERATED",
    licenseOrApprovalReference: approvalReference,
    fictionalSubject: true,
    filePath: "media/staff/processing-manager.webp",
    sha256: "d83c3d90d5268c9d985428faeb5fac8be610e15f900801e7d800d5d5024b985f",
    width: 480,
    height: 600,
    format: "webp",
    developmentPlaceholder: false,
  },
  {
    assetId: PortraitAssetId.SHIPPING_CLERK,
    sourceType: "AI_GENERATED",
    licenseOrApprovalReference: approvalReference,
    fictionalSubject: true,
    filePath: "media/staff/shipping-clerk.webp",
    sha256: "f51510f254decd6ff1fb03844300238b6942e4381f21ae53dd97dc4977af2fc5",
    width: 480,
    height: 600,
    format: "webp",
    developmentPlaceholder: false,
  },
  {
    assetId: PortraitAssetId.RETAIL_MANAGER,
    sourceType: "AI_GENERATED",
    licenseOrApprovalReference: approvalReference,
    fictionalSubject: true,
    filePath: "media/staff/retail-manager.webp",
    sha256: "12aa24499b1b73d608d93f4e527d7f4748e85ab85b02dc634b863daa35f10fae",
    width: 480,
    height: 600,
    format: "webp",
    developmentPlaceholder: false,
  },
  {
    assetId: PortraitAssetId.REGULATORY_AUDITOR,
    sourceType: "AI_GENERATED",
    licenseOrApprovalReference: approvalReference,
    fictionalSubject: true,
    filePath: "media/staff/regulatory-auditor.webp",
    sha256: "25a7526bb2258722e7a6febed2a03f2397346ff71a3a5fe260badeda6a1ea4c5",
    width: 480,
    height: 600,
    format: "webp",
    developmentPlaceholder: false,
  },
];

export const coffeeStaffProfiles: readonly ScenarioStaffProfile[] = [
  {
    staffProfileId: StaffProfileId.PRODUCER_MANAGER,
    actorId: ActorId.PRODUCER_MANAGER,
    roleId: "PRODUCER_MANAGER",
    displayNameKey: "staff.producerManager.name",
    roleTitleKey: "staff.producerManager.role",
    organizationId: OrganizationId.PRODUCER_COOP,
    locationId: LocationId.PRODUCER_FARM,
    departmentKey: "staff.producerManager.department",
    portraitAssetId: PortraitAssetId.PRODUCER_MANAGER,
    portraitAltKey: "staff.producerManager.alt",
    shortProfileKey: "staff.producerManager.profile",
    professionalResponsibilityKey: "staff.producerManager.responsibility",
    visibility: "LEARNER_VISIBLE",
    fictional: true,
  },
  {
    staffProfileId: StaffProfileId.CERTIFICATION_OFFICER,
    actorId: ActorId.CERTIFICATION_OFFICER,
    roleId: "CERTIFICATION_OFFICER",
    displayNameKey: "staff.certificationOfficer.name",
    roleTitleKey: "staff.certificationOfficer.role",
    organizationId: OrganizationId.CERTIFICATION_BODY,
    departmentKey: "staff.certificationOfficer.department",
    portraitAssetId: PortraitAssetId.CERTIFICATION_OFFICER,
    portraitAltKey: "staff.certificationOfficer.alt",
    shortProfileKey: "staff.certificationOfficer.profile",
    professionalResponsibilityKey: "staff.certificationOfficer.responsibility",
    visibility: "LEARNER_VISIBLE",
    fictional: true,
  },
  {
    staffProfileId: StaffProfileId.LOGISTICS_COORDINATOR,
    actorId: ActorId.LOGISTICS_COORDINATOR,
    roleId: "LOGISTICS_COORDINATOR",
    displayNameKey: "staff.logisticsCoordinator.name",
    roleTitleKey: "staff.logisticsCoordinator.role",
    organizationId: OrganizationId.LOGISTICS_PROVIDER,
    locationId: LocationId.TRANSIT_STATION,
    portraitAssetId: PortraitAssetId.LOGISTICS_COORDINATOR,
    portraitAltKey: "staff.logisticsCoordinator.alt",
    shortProfileKey: "staff.logisticsCoordinator.profile",
    professionalResponsibilityKey: "staff.logisticsCoordinator.responsibility",
    visibility: "LEARNER_VISIBLE",
    fictional: true,
  },
  {
    staffProfileId: StaffProfileId.PROCESSING_MANAGER,
    actorId: ActorId.PROCESSING_MANAGER,
    roleId: "PROCESSING_MANAGER",
    displayNameKey: "staff.processingManager.name",
    roleTitleKey: "staff.processingManager.role",
    organizationId: OrganizationId.COFFEE_PROCESSOR,
    locationId: LocationId.PROCESSING_PLANT,
    portraitAssetId: PortraitAssetId.PROCESSING_MANAGER,
    portraitAltKey: "staff.processingManager.alt",
    shortProfileKey: "staff.processingManager.profile",
    professionalResponsibilityKey: "staff.processingManager.responsibility",
    visibility: "LEARNER_VISIBLE",
    fictional: true,
  },
  {
    staffProfileId: StaffProfileId.SHIPPING_CLERK,
    actorId: ActorId.SHIPPING_CLERK,
    roleId: "SHIPPING_CLERK",
    displayNameKey: "staff.shippingClerk.name",
    roleTitleKey: "staff.shippingClerk.role",
    organizationId: OrganizationId.PRODUCER_COOP,
    locationId: LocationId.PRODUCER_FARM,
    portraitAssetId: PortraitAssetId.SHIPPING_CLERK,
    portraitAltKey: "staff.shippingClerk.alt",
    shortProfileKey: "staff.shippingClerk.profile",
    professionalResponsibilityKey: "staff.shippingClerk.responsibility",
    visibility: "LEARNER_VISIBLE",
    fictional: true,
  },
  {
    staffProfileId: StaffProfileId.RETAIL_MANAGER,
    actorId: ActorId.RETAIL_MANAGER,
    roleId: "RETAIL_MANAGER",
    displayNameKey: "staff.retailManager.name",
    roleTitleKey: "staff.retailManager.role",
    organizationId: OrganizationId.RETAILER,
    locationId: LocationId.RETAIL_STORE,
    portraitAssetId: PortraitAssetId.RETAIL_MANAGER,
    portraitAltKey: "staff.retailManager.alt",
    shortProfileKey: "staff.retailManager.profile",
    professionalResponsibilityKey: "staff.retailManager.responsibility",
    visibility: "LEARNER_VISIBLE",
    fictional: true,
  },
  {
    staffProfileId: StaffProfileId.REGULATORY_AUDITOR,
    actorId: ActorId.REGULATORY_AUDITOR,
    roleId: "REGULATORY_AUDITOR",
    displayNameKey: "staff.regulatoryAuditor.name",
    roleTitleKey: "staff.regulatoryAuditor.role",
    organizationId: OrganizationId.REGULATOR,
    departmentKey: "staff.regulatoryAuditor.department",
    portraitAssetId: PortraitAssetId.REGULATORY_AUDITOR,
    portraitAltKey: "staff.regulatoryAuditor.alt",
    shortProfileKey: "staff.regulatoryAuditor.profile",
    professionalResponsibilityKey: "staff.regulatoryAuditor.responsibility",
    visibility: "LEARNER_VISIBLE",
    fictional: true,
  },
];

export const coffeeEvidenceStaffAttributions:
  readonly ScenarioEvidenceStaffAttribution[] = [
    {
      evidenceId: SHIPPING_MANIFEST_ANCHOR_ID,
      staffProfileId: StaffProfileId.SHIPPING_CLERK,
      relationship: "AUTHORED",
      occurredAt: "2026-01-18T06:45:00.000Z",
    },
  ];
